global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'react-app-metrics-production'
    static_configs:
      - targets: ['react-metrics-production.up.railway.app:443']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scheme: https

  - job_name: 'react-app-metrics-local'
    static_configs:
      - targets: ['metrics-server:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
