global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'react-app-metrics'
    static_configs:
      - targets: ['metrics-server:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
